### ISSUE TITLE
Question: exposing constructor parameters (e.g. preserveDrawingBuffer)

### ISSUE THREAD

**Issue by vphilot** [troisjs/trois#117]
is there a way to provide constructor params when instantiating a renderer with Trois? There are some options that can only be provided when the rendered is instantiated, e.g. `preserveDrawingBuffer`. 

ref: https://threejs.org/docs/#api/en/renderers/WebGLRenderer.preserveDrawingBuffer

**Comment by SaFrMo** [comment]
There isn't a way right now, but that's a good idea for a feature - the renderer's instantiation is hardcoded [here](https://github.com/troisjs/trois/blob/master/src/core/useThree.ts#L99), so that'd be the place to change it. @klevron I can take a look at this in the next week or two, let me know if you'd prefer to take it!

**Comment by klevron** [comment]
Thanks @vphilot for reporting this, it will be possible in next version
@SaFrMo: thanks, already done :)

**Comment by vphilot** [comment]
thanks for the amazing work @klevron @SaFrMo
