### ISSUE TITLE
Composition API

### ISSUE THREAD

**Issue by joshuavachon25** [troisjs/trois#97]
All the examples in the documentation concern the option API, is there a reason composition API is not use? Else, how would do it (example with a box rotation)?

Thanks

**Comment by SaFrMo** [comment]
You should be able to use the composition API like normal, you just need to wait for components to be added in `onMounted`. You can do something like (translated from [the docs](https://troisjs.github.io/guide/core/raf.html)):

```html
<template>
  <Renderer ref="renderer">
    <Camera :position="{ z: 10 }" />
    <Scene>
      <PointLight :position="{ y: 50, z: 50 }" />
      <Box ref="box" :rotation="{ y: Math.PI / 4, z: Math.PI / 4 }">
        <LambertMaterial />
      </Box>
    </Scene>
  </Renderer>
</template>

<script setup>
import { onMounted, ref } from 'vue'
const renderer = ref()
const box = ref()

onMounted(() => {
    renderer.value.onBeforeRender(() => {
        box.value.rotation.x += 0.01;
    }
})
</script>
```

You may need to do some digging inside the refs (for example, `renderer.value.$el.onBeforeRender` instead of `renderer.value.onBeforeRender) to get to the right properties, but they should be available. Let me know if they're not and I can take another look!

**Comment by klevron** [comment]
Please read this about reactivity : https://troisjs.github.io/guide/core/raf.html

> don't use reactivity to update troisjs components, you should directly update ThreeJS objects
